### PR TITLE
📦 #58 Block Generation

### PR DESCRIPTION
**Pull request by roma-glushko**
### Description (*)
This PR provides an additional action that helps to generate new block components.

### Fixed Issues (if relevant)
1. magento/magento2-phpstorm-plugin#58: Action/Code Generation. Block generation

### Contribution checklist (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

### CODE REVIEW

**Comment by Vinai** [comment]
How about adding a little note to the New Block dialogue:
"Please consider creating a view model instead of a block if possible for your use case".

**Comment by VitaliyBoyko** [comment]
Hi @Vinai 
Makes sense.

**Comment by Vinai** [comment]
Love your work here btw 👍

**Comment by VitaliyBoyko** [comment]
Thanks!

**Pull request merged**
