### PR TITLE
900: Changed realization for function checkDelete using of CheckUtil.

### PR DESCRIPTION
**Pull request by artemii-karkusha**
**Description** (*)

I think we have two variants. We should set this method how deprecated and never use xmlTag.checkDelete() or create another realisation for it. I found service CheckUtil which has realisation checkWritable (similar checkDelete) for PsiElement. 

**Fixed Issues (if relevant)**

1. Fixes Eliminate LineMarkerXmlTagDecorator#checkDelete usage #900

**Contribution checklist** (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with integration/functional tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by bohdan-harniuk — APPROVED** [review]
Hello, @artemii-karkusha!

Thank you for your work here!

**Comment by bohdan-harniuk** [comment]
Hello, @artemii-karkusha!

Please, make your branch up to date with the 4.2.2-develop.

**Comment by artemii-karkusha** [comment]
Hello, @bohdan-harniuk 
I updated my branch from 4.2.2-develop. Thank you.

**Comment by bohdan-harniuk** [comment]
@artemii-karkusha, 👌

**Pull request merged**
