### PR TITLE
966 add a placeholders to create new controller form

### PR DESCRIPTION
**Pull request by SilinMykola**
**Description** (*)
I added the placeholders to the 'Create new Controller' form.
actionPath

**Fixed Issues (if relevant)**
1. Fixes magento/magento2-phpstorm-plugin#960

**Questions or comments**

**Contribution checklist** (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with integration/functional tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by SilinMykola** [comment]
@eduard13 hi! Could you please review the PR and tell me what you think about the placeholders on this form. Will the input fields be understandable with this kind of placeholders?
CC: @lfolco hello! What do you think about these placeholders? Would that be helpful?

**Comment by lfolco** [comment]
Still not sure exactly what is being asked for in these: is _Controller Name_ supposed to be something along the lines of _catalog/product/view_?

**Comment by bohdan-harniuk** [comment]
Hello, @lfolco!

Yes, controller name for the provided path `catalog/product/view` is a Product.
How do you think it would be better to describe it in the placeholder?

Regards,

**Comment by lfolco** [comment]
After testing it locally, I think the labels should be `Action Name` and `Action Path`. Placeholder can be _Class name for Action_ and _Folder name for Action_.

Unless the plugin has been changed, it doesn't look like it's doing anything along the lines of `catalog/product/view`.

Also, it doesn't create a proper namespace. When I fill it in like this:

image

I get a class with a namespace like this:

image

What exactly is `Parent Directory` supposed to be? You can't change it from what I can see.

**Comment by bohdan-harniuk** [comment]
@lfolco, you have outdated plugin version. Please, update it and try it again. Everything should works fine with namespaces.
Parent directory is a constant value. It doesn't matter because all controllers always are in the Controller folder.

Regards,

**Comment by SilinMykola** [comment]
@lfolco Hello! I think you are right. I changed labels and placeholders. Our goal is to make controller creation more understandable for everyone. Please, check new variants. Thanks!
actionPath
CC: @bohdan-harniuk Hi! What do you think about these changes? Thanks!

**Comment by bohdan-harniuk** [comment]
Hello, @SilinMykola, @lfolco!

I think you made great improvements here!

Thank you!

**Review by bohdan-harniuk — APPROVED** [review]
Great work!

**Comment by lfolco** [comment]
This looks great, thank you!

**Pull request merged**
