### PR TITLE
Fixed interface plugin linemarker

### PR DESCRIPTION
**Pull request by drpayyne**
**Description**

This PR fixes the missing linemarker for plugins to interface methods

**Fixed Issues**

1. magento/magento2-phpstorm-plugin#322: Plugin linemarkers is missing for interface methods

**Questions or comments**

I have a proposed solution, but if anyone has a better solution, please do let me know. I shall improve it. 

**Contribution checklist**
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with integration/functional tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by drpayyne** [comment]
Please check the first commit in this PR (ref: https://github.com/magento/magento2-phpstorm-plugin/pull/328/commits/a17b6a3df81abbe92d46b6aa8c0f3bab457c4037) to find my proposed solution. The other commit adds too many static test fixes. 

Also, I was thinking if the below code would be a better approach than the one in the above commit. This code would get both classes and interfaces, for the given FQN, instead of just getting interfaces only if classes returned empty. Is there a case where the below code would be required? Just bouncing off ideas, thanks.
```
for (String targetClassName : targetClassNames) {
    Collection<PhpClass> targets = phpIndex.getClassesByFQN(targetClassName);
    targets.addAll(phpIndex.getInterfacesByFQN(targetClassName));
    results.addAll(targets);
}
```

**Comment by drpayyne** [comment]
This PR edits a single line of a file where there are 10s of pre-existing static test failures. I shall fix those failures once my suggested approach is confirmed by a reviewer. Thanks!

**Comment by VitaliyBoyko** [comment]
@drpayyne I'm fine with the solution. Please proceed.

**Comment by drpayyne** [comment]
Hi @VitaliyBoyko, could you please advise on how I can fix the remaining static test failures? I'm not sure what's the good approach.
```
/home/runner/work/magento2-phpstorm-plugin/magento2-phpstorm-plugin/src/com/magento/idea/magento2plugin/linemarker/php/PluginTargetLineMarkerProvider.java:79:	Avoid using implementation types like 'HashMap'; use the interface instead

/home/runner/work/magento2-phpstorm-plugin/magento2-phpstorm-plugin/src/com/magento/idea/magento2plugin/linemarker/php/PluginTargetLineMarkerProvider.java:132:	To avoid mistakes add a comment at the beginning of the TargetClassesCollector constructor if you want a default access modifier

/home/runner/work/magento2-phpstorm-plugin/magento2-phpstorm-plugin/src/com/magento/idea/magento2plugin/linemarker/php/PluginTargetLineMarkerProvider.java:147:	To avoid mistakes add a comment at the beginning of the TargetMethodsCollector constructor if you want a default access modifier
```

**Review by VitaliyBoyko — APPROVED** [review]
QA passed ✅ 

image

**Pull request merged**
