### PR TITLE
Added resource to web API dialog form

### PR DESCRIPTION
**Pull request by anzin**
**Description** (*)

I've added all ACL resources to the web API dialog form.

**Result**:
image

image

**Contribution checklist** (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with integration/functional tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @anzin, thank you for contribution. Can we have a restriction to always select a value from dropdown? Currently, we can enter and submit the form having a wrong ACL entered.
image

Thank you.

**Comment by anzin** [comment]
Hello @eduard13  thank you for your check, I will do a restriction to always select a value from the dropdown.

**Comment by eduard13** [comment]
Hi @anzin, are you willing to continue the progress on this PR?

Thank you.

**Comment by anzin** [comment]
Hello @eduard13, I've added a restriction to always select a value from the dropdown.

**Review by eduard13 — APPROVED** [review]
Looks great 👍

**Pull request merged**
