### PR TITLE
1171: Override template in a module

### PR DESCRIPTION
**Pull request by SilinMykola**
**Description** (*)
Added to the action menu item to override a template in a module.

**Fixed Issues (if relevant)**
1. Fixes magento/magento2-phpstorm-plugin#<issue_number>

**Questions or comments**

**Contribution checklist** (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with integration/functional tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by bohdan-harniuk — APPROVED** [review]
Hello, @SilinMykola!
Great work!
Thank you!

**Comment by sdouma** [comment]
@SilinMykola  Can you tell us why did this branch(magento:mainline/1171-overriding-template-in-a-module) got deleted and not merged in?

**Comment by SilinMykola** [comment]
@sdouma hi!  I don't remember exactly what happened but I think that we decided to make this feature in another plugin.

**Comment by sdouma** [comment]
> @sdouma hi! I don't remember exactly what happened but I think that we decided to make this feature in another plugin.

Thank you, please let me know if you remember the plugin.

**Comment by SilinMykola** [comment]
@sdouma [plugin](https://plugins.jetbrains.com/plugin/20554-magento-and-adobe-commerce-phpstorm-by-atwix), but I don't know if they already implemented the functionality or not.

**Pull request merged**
