### PR TITLE
1050: added raw plugin verifier configuration

### PR DESCRIPTION
**Pull request by doninAtwix**
**Description** (*)
Added raw plugin verifier configuration.
Screenshot 2022-04-14 at 11 24 53
Screenshot 2022-04-14 at 11 29 37
Screenshot 2022-04-14 at 11 32 40

**Fixed Issues (if relevant)**

1. Fixes magento/magento2-phpstorm-plugin#1050

**Questions or comments**

**Contribution checklist** (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with integration/functional tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by doninAtwix** [comment]
> Hello, @doninAtwix!
> 
> Please, update your branch from the mainline. Did you checked if this configuration is working?
> 
> Regards,

Hi @bohdan-harniuk .
Branch updated. Yes it has been tested and this configuration works as expected.

Thank you

**Comment by bohdan-harniuk** [comment]
@doninAtwix, could you please provide some screenshots?

**Comment by doninAtwix** [comment]
> @doninAtwix, could you please provide some screenshots?

Description updated, please check again.

**Review by bohdan-harniuk — APPROVED** [review]
Hello, @doninAtwix!

Thank you for your work here!

**Pull request merged**
