### PR TITLE
Added reference navigation for observer name

### PR DESCRIPTION
**Pull request by drpayyne**
**Description**

This PR adds
- reference navigation for observer name
- test coverage

**Fixed Issues**

1. Fixes magento/magento2-phpstorm-plugin#423: Reference navigation for disabled observers

**Contribution checklist**
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with integration/functional tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by VitaliyBoyko** [comment]
Hi @drpayyne 

Are you up to proceed with this?

**Comment by drpayyne** [comment]
Hi @VitaliyBoyko, yes I believe this still requires a review? I had contacted @coderimus regarding the unrelated test failures but not sure about it. So I'd need help figuring out why these tests are failing. Thanks!

**Comment by VitaliyBoyko** [comment]
@drpayyne Could you please fix conflicts then?

**Comment by drpayyne** [comment]
Done, @VitaliyBoyko!

**Comment by VitaliyBoyko** [comment]
So only static tests are falling. Could you please fixe them?

**Review by coderimus — APPROVED** [review]
@drpayyne thank you for the implementation. Approved!

**Pull request merged**
