### PR TITLE
Changed new controller dialog validator

### PR DESCRIPTION
**Pull request by drpayyne**
**Description**

This PR adds validation through annotations to the new controller dialog and removes the unnecessary `com.magento.idea.magento2plugin.actions.generation.dialog.validator.NewControllerValidator`

**Fixed Issues**

1. magento/magento2-phpstorm-plugin#297: Change validation for the new controller dialog window

**Contribution checklist** (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with integration/functional tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by VitaliyBoyko** [comment]
QA failed 

Case:
controller should begin with the capital letter ⛔ 
image
wrong exception message
image

Same for action name. 
Please check all the cases and messages.

**Review by VitaliyBoyko — CHANGES_REQUESTED** [review]
Please consider checking all validation cases.

**Comment by drpayyne** [comment]
Hi @VitaliyBoyko, I've fixed the issues. Please review. Thanks!

**Review by VitaliyBoyko — CHANGES_REQUESTED** [review]
QA failed ⛔ 
Fill out the `Controller Name` with the not valid symbols.
image
Wrong message
image

For the `Action Name` works well. ✅ 
image

**Comment by drpayyne** [comment]
@VitaliyBoyko, controller name already does a `namespace` check. Would it be better if we fix that instead of adding another rule to this field to limit it to alphanumeric?

**Comment by VitaliyBoyko** [comment]
> @VitaliyBoyko, controller name already does a `namespace` check. Would it be better if we fix that instead of adding another rule to this field to limit it to alphanumeric?

Yes

**Comment by drpayyne** [comment]
Hi @VitaliyBoyko, I've remove the `PhpNamespaceRule` check and instead used `AlphanumericRule` check. The namespace rule actually _only_ checks if the value is a PHP identifier and not a reserved keyword. This doesn't work for our use case.

**Comment by VitaliyBoyko** [comment]
⛔  

image
image

Classes names can begin from a number.

**Review by VitaliyBoyko — CHANGES_REQUESTED** [review]
Please check the case with a number at the beginning of a class name.

**Comment by drpayyne** [comment]
Hi @VitaliyBoyko, all these validations have confused me on valid PHP namespaces and PHP classes. Can you please check the below links and guide me on how to proceed?
- https://www.php.net/manual/en/language.namespaces.rationale.php#104196
- https://www.php.net/manual/en/language.oop5.basic.php (2nd paragraph)

Thanks.

**Review by VitaliyBoyko — APPROVED** [review]

**Pull request merged**
