### PR TITLE
955 add missing title to form

### PR DESCRIPTION
**Pull request by SilinMykola**
**Description** (*)
I added missed titles to some forms.
Magento 2 Email Template form:
image

and Magento 2 Models form: 
image

**Fixed Issues (if relevant)**

1. Fixes magento/magento2-phpstorm-plugin#955
**Questions or comments**

**Contribution checklist** (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with integration/functional tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by eduard13 — CHANGES_REQUESTED** [review]
Hi @SilinMykola, thank you for the fix, may I ask you to also adjust the title for Models modal? The single form should be used: `models` -> `model`.

Thank you.

**Comment by SilinMykola** [comment]
Hi @eduard13 ! Thanks for your review. I added the title to both modal windows:  'Magento 2 Email Template' and 'Magento 2 Models'. Also, I added two screenshots to the description.
Have a nice day!

**Review by bohdan-harniuk — APPROVED** [review]
Hello, @SilinMykola!

Thank you for your contribution and for fixing after @eduard13 review.

**Comment by bohdan-harniuk** [comment]
Hello, @eduard13!

Please, check the PR. It is fixed.

Regards,

**Review by eduard13 — APPROVED** [review]

**Pull request merged**
