### PR TITLE
414: Added Images support for Copy Magento Path

### PR DESCRIPTION
**Pull request by doninAtwix**
**Description** (*)
Added Images support for Copy Magento Path.
Used ImageIO extension support for images.

Screenshot 2022-02-28 at 12 40 36
Screenshot 2022-02-28 at 12 39 04
Screenshot 2022-02-28 at 12 38 47
Screenshot 2022-02-28 at 12 38 31
Screenshot 2022-02-28 at 12 38 06
Screenshot 2022-02-28 at 12 37 42
Screenshot 2022-02-28 at 12 37 27

**Fixed Issues (if relevant)**

1. Fixes magento/magento2-phpstorm-plugin#414

**Questions or comments**

**Contribution checklist** (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with integration/functional tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by bohdan-harniuk** [comment]
Hello, @eduard13!

This PR is created to finish https://github.com/magento/magento2-phpstorm-plugin/pull/559.
Could you please check, if your suggestions were implemented?

Regards,

**Review by eduard13 — APPROVED** [review]
Exactly what I was looking for. Great job 👏

**Comment by bohdan-harniuk** [comment]
@eduard13, thank you!

**Review by bohdan-harniuk — APPROVED** [review]
Hello, @doninAtwix!

Thank you for your work here!

Regards,

**Pull request merged**
