### PR TITLE
#184 Setup Code Style Checks 📦

### PR DESCRIPTION
**Pull request by roma-glushko**
### Description
This PR introduces static code checks:
- [Checkstyle](https://docs.gradle.org/current/userguide/checkstyle_plugin.html)
- [PMD](https://docs.gradle.org/current/userguide/pmd_plugin.html#header)
- [Spotbugs](https://github.com/spotbugs/spotbugs-gradle-plugin)

### Fixed Issues
* magento/magento2-phpstorm-plugin#184: Setup Code Style Checks

### Contribution checklist 
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages

### CODE REVIEW

**Comment by VitaliyBoyko** [comment]
Let's temporarily suppress all the existing .java files. What do you think?

**Comment by coderimus** [comment]
@VitaliyBoyko I think that we can get more benefits if all style checks are fixed in the scope of this PR. The 1.0.1 release, as I can see, has a lot of new feature requests and while they are in progress we can adopt already existed code base to the best practices according to standads.

@roma-glushko maybe we have something similar to the phpcs fixer in the Java world :) if yes we can automatically fix tons of warnings such as spaces and general formatting issue.

If we can split code style issues between us I am ready to help.

**Comment by VitaliyBoyko** [comment]
@coderimus Got you point, let me create then kinda' epic branch. Then we will able to make PRs there.

**Comment by VitaliyBoyko** [comment]
However, I'm afraid we break something during refactoring.

**Comment by VitaliyBoyko** [comment]
Maybe it better to fix it in small portions 🤔

**Comment by VitaliyBoyko** [comment]
Here we go `184-code-styling-epic`

**Comment by coderimus** [comment]
@VitaliyBoyko I like that idea about the small portions and test coverage. What about granulated work per action? This will allow making the process more organized and connect other project members.

> However, I'm afraid we break something during refactoring.

Yep. I think we will find and fix already existed bugs :)

**Comment by VitaliyBoyko** [comment]
Let's discuss it at a meeting. I see some additional points to cover.

**Comment by roma-glushko** [comment]
@VitaliyBoyko @coderimus thank you for your attention to this PR 🙌 

At this point, we can see that there are still a couple of active static check project in Java we can try to use 😄 

However, each of these three tools reports 2k+ warnings/errors which we can not fix over the night. So my next steps here are:
- review issues that each of the tool reports to see whether they make sense for the project
- reduce checking scope to PR changeset only (otherwise, we will break every next PR in the project)
- try to fix at least code style issues somehow automatically 

I will proceed working on this draft and let you know when I investigate the mentioned points.

**Comment by VitaliyBoyko** [comment]
Changed back to `1.0.1-develop` according to our personal discussion.

**Pull request merged**
