### PR TITLE
262: Change the CLI command namespace

### PR DESCRIPTION
**Pull request by coderimus**
**Description** (*)
This PR provides changes to the CLI command namespace. According to the standards, the command class should be located at the `Vendor\Console\Command` namespace.

**Fixed Issues (if relevant)**
#262 

**Questions or comments**
N/A

**Contribution checklist** (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [x] All new or changed code is covered with integration/functional tests (if applicable)
 - [x] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by coderimus** [comment]
@VitaliyBoyko thank you for help with this issue 👍 . I also return to it :)

**Comment by coderimus** [comment]
Hi @VitaliyBoyko ,
Please, review the provided changes. I fixed the tests for the Windows build and also added a line to the gradle build configuration: 
```
gradle.startParameter.showStacktrace = org.gradle.api.logging.configuration.ShowStacktrace.ALWAYS_FULL
```
It helps to see the stack trace on builds :)

**Comment by coderimus** [comment]
@magento run all tests

**Comment by coderimus** [comment]
@magento run build-linux

**Comment by coderimus** [comment]
@VitaliyBoyko please, review the changes. The actual result with them is next:
image

image

**Review by VitaliyBoyko — APPROVED** [review]
QA passed ✅ 
image

**Pull request merged**
