### PR TITLE
Use appropriate product name in inspections

### PR DESCRIPTION
**Pull request by Vinai**
**Description**

There are two official names: "Magento Open Source" and "Adobe Commerce".
As the product "Magento Open Source" is the foundation of "Adobe Commerce" because "Adobe Commerce" can not be used without "Magento Open Source", and since the plugin works for either, using "Magento Open Source" is a more appropriate name for anything that applies to both "Magento Open Source" and "Adobe Commerce".

The name "Adobe Commerce" is appropriate for anything that is exclusive to  "Adobe Commerce" and does not apply to "Magento Open Source".

**Describe alternatives you've considered**

An alternative would be to always explicitly name both products, as in "Magento Open Source or Adobe Commerce" but that is excessively long.

**Additional context**

Personally I think it would be better to only use the name "Magento" for readability when referring to both products, but probably that won't fly with Adobe.

**Reference Issue https://github.com/magento/magento2-phpstorm-plugin/issues/828**

### CODE REVIEW

**Comment by sivaschenko** [comment]
Hi @Vinai , Magento Open Source is a part of Adobe Commerce, the inspections are designed to be compatible with any Adobe Commerce code (including Magento Open Source).

I know it may be a challenge after so many years with Magento, but we should get used to the new branding.

I don't think it makes sense to change the naming in the messages.

**Comment by Vinai** [comment]
@sivaschenko Since Adobe Commerce installs are a subset of all Magento based installs, I think it is not just a matter of branding, but actually an important distinction.

> the inspections are designed to be compatible with any Adobe Commerce code (including Magento Open Source)

This doesn't quite reflect reality.

1. What name would you use for a feature that is only compatible with Adobe Commerce?
  
2. What name would you use for a feature that is only compatible with Magento Open Source?

3. What name would you use for a feature that is compatible with both?

Since all three things exist in this world, it is important to have names that state this clearly.

**Comment by sivaschenko** [comment]
Hi @Vinai each feature naming can be discussed individually. The messages updated in this pull request are referencing Adobe Commerce specifically.

**Comment by Vinai** [comment]
> The messages updated in this pull request are referencing Adobe Commerce specifically.

No, the features are also available in Magento Open Source.

> I know it may be a challenge after so many years with Magento, but we should get used to the new branding.

I have gotten used to calling the commercial product built on top of Magento Open Source "Adobe Commerce" instead of "Enterprise Edition".  
I don't understand why you are suggesting "Magento Open Source" be called "Adobe Commerce"?

> Magento Open Source is a part of Adobe Commerce, the inspections are designed to be compatible with any Adobe Commerce code (including Magento Open Source).

The inspection names should express that, and currently they don't.
All Adobe Commerce Installations are a small subset of all Magento Open Source Code Installations.
Naming the inspections "Adobe Commerce" doesn't reflect this.
No matter how you slice the cake - by number of installations or lines of code - naming the inspections Adobe Commerce is not accurate.

```
+--------------------------------------------------------------------------+
|                                                                          |
|                                                                          |
|                 Magento Open Source Code Installations                   |
|                                                                          |
|                                                                          |
|                                                                          |
|                                                                          |
|                                                                          |
|                                                                          |
|                                                                          |
|                                                                          |
|                                                                          |
|                                                                          |
|                        Magnified                                         |
|                             +--+                                         |
|                             +--+                                         |
|                             |                                            |
|                             |                                            |
|                             |                                            |
|                             +------->+-------------+                     |
|                                      |Adobe        |                     |
|                                      |Commerce     |                     |
|                                      |Installations|                     |
|                                      +-------------+                     |
|                                                                          |
+--------------------------------------------------------------------------+
```

Are you aware that this kid of behavior and attempt to "brand" the open source product is part of why many of the Magento developer community feel alienated?

From my point of view honest response to this PR would be:

"This plugin is maintained by Adobe employees during working hours, and as such Adobe gets to choose what names to use."

Anything argument that Adobe Commerce is more appropriate because it is built on top of Magento Open Source seems weak.

**Comment by bohdan-harniuk** [comment]
Hello, @Vinai!

So, I think we can go farther with it and replace the default Adobe Commerce to the concrete platform version (dynamically resolved):

1. Magento Open Source
2. Adobe Commerce

What do you think?

Thanks,
Bohdan

**Comment by Vinai** [comment]
@bohdan-harniuk That would work. Seems like more work than what would be necessary, but it would be accurate naming.

**Comment by bohdan-harniuk** [comment]
@Vinai, Then I'll proceed with development in your PR.

**Comment by Vinai** [comment]
Thank you! - Feel free to start on a new branch if you prefer!

**Comment by sivaschenko** [comment]
@Vinai the messages are referencing code (i.e. classes for this example), not project/installations.

Any class mentioned in the message can be referenced as Adobe Commerce class (as Adobe Commerce code base include Magento Open Source).
Only some of the classes can be referenced as Magento Open Source.
Dynamic product name resolution is a compromise solution but looks to me as an overhead.

I don't have anything against updating the messages if they are confusing. Just sharing my honest personal (not Adobe) opinion.

**Comment by bohdan-harniuk** [comment]
Hello, @Vinai!

This issue resolved by @doninAtwix in the #828.
I'm closing this PR.

Thank you!

**Pull request closed without merging**
