### PR TITLE
#issue-179 Added email template generation

### PR DESCRIPTION
**Pull request by serhiyzhovnir**
**Description** (*)
This PR adds the generation for the email templates.

Screenshot 2020-10-24 at 12 55 15
Screenshot 2020-10-24 at 12 56 07
Screenshot 2020-10-24 at 12 56 35
Screenshot 2020-10-24 at 12 56 49

**Fixed Issues (if relevant)**

1. Fixes magento/magento2-phpstorm-plugin#179

**Contribution checklist** (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with integration/functional tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by VitaliyBoyko** [comment]
I believe the possible area should be always fronted, shouldn’t it?

**Comment by serhiyzhovnir** [comment]
Hi @VitaliyBoyko 
Thank you for your question.
The adminhtml and frontend areas are allowed.
Here are proofs from Magento core:
Screenshot 2020-10-24 at 13 37 18

**Review by coderimus — CHANGES_REQUESTED** [review]
Hello @serhiyzhovnir 
Thank you for the provided improvement. It will help a lot for the development process improvement.

I made some tests and found failed scenarios. Please, check my report below:

**Scenario 1**
1. Create a template for the frontend area. Let's name it `custom_template`
2. Start creating a new template for the frontend area. Choose the `custom_template` name for the template.
3. When you will try to creat it, you will get an error reported that the file custom_template.html already exists. This is correct. But in the `email_templates.xml` we will have an entry. Please, change this to the next: when an error appeared during the create template action we should not update the XML config file.
image

**Scenario 2**
1. Try to create templates with the same id
2. Current result: nodes in the `email_templates.xml` has the same id. I think this is a bug. We should not allowed create email templates with the same id for the selected area
image

**Comment by VitaliyBoyko** [comment]
@serhiyzhovnir 

Are you up to proceed with this?

**Comment by serhiyzhovnir** [comment]
Hi @VitaliyBoyko 
Could you check the adjustments?
Thank you!

**Comment by VitaliyBoyko** [comment]
Hey @coderimus please proceed with this.

**Comment by coderimus** [comment]
@VitaliyBoyko will process it before lunch today.

**Review by coderimus — CHANGES_REQUESTED** [review]
@serhiyzhovnir
I fetched and pulled the latest changes from the PR branch. When I tried to test the latest revision I faced the next problem: when I open a new email template generation form an error occurred and nothing happened on pressing OK button. Please, validate Null pointer exception. CC @VitaliyBoyko 
image

**Comment by serhiyzhovnir** [comment]
Hi @coderimus 
The issue with the Null pointer is fixed.
May you review this again?
Thanks.

**Comment by coderimus** [comment]
@serhiyzhovnir thank you for the quick fix 👍 The problem gone and the issue I reported previously also fixed. QA passed. Approved 👍

**Review by coderimus — APPROVED** [review]

**Pull request merged**
