### PR TITLE
1206: Covered possible NullPointerException in InjectAViewModelDialog.java

### PR DESCRIPTION
**Pull request by Mgonzalez-droid**
**Description** (*)

I added conditional logic to test if the given variable is null, if null we will return and avoid execution of the code that could through a NPE. If the code is fine then it will continue as normal.

**Fixed Issues (if relevant)**

1. Fixes magento/magento2-phpstorm-plugin#1206

**Contribution checklist** (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with integration/functional tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by Mgonzalez-droid** [comment]
Let me know if there is anything else I might have missed, Thank you again for your help!

**Review by bohdan-harniuk — CHANGES_REQUESTED** [review]
Hello, @Mgonzalez-droid!
Please, take a look at my suggestion.
Regards,

**Comment by bohdan-harniuk** [comment]
Hello, @Mgonzalez-droid!
I've shown for you how to make condition easier.
Please, read what you have submitted.
It should be done **by hands**, not via GitHub shortcut.
Not code is broken.
Regards,

**Comment by Mgonzalez-droid** [comment]
I went ahead and made the change you suggested, made a mistake by assuming git would correctly format the code how you suggested. Do apologize, this latest commit should be what you were looking for. If not let me know and I will address it right away. Thank you!

**Comment by bohdan-harniuk** [comment]
@Mgonzalez-droid, there is no need to keep **else** clause. Take a look at line **140**:
```java
 if (!validateFormFields()) {
            exit();
            return;
        }
```
There is no **else**. Adding **else** here makes it more nested without any particular reason.
Regards,

**Comment by bohdan-harniuk** [comment]
Hello, @Mgonzalez-droid!
Any updates here?
Regards,

**Review by VitaliyBoyko — APPROVED** [review]

**Review by VitaliyBoyko — APPROVED** [review]

**Pull request merged**
