### PR TITLE
#186: Extend the new Magento 2 module generation with the ability to …

### PR DESCRIPTION
**Pull request by mmezhensky**
**Description** (*)

This PR extends the new Magento 2 module generation with the ability to set module sequence(s).

**Fixed Issues (if relevant)**

1. magento/magento2-phpstorm-plugin#186: Extend action / Code Generation. Add ability to set the module sequence at generating new module.

**Contribution checklist** (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with integration/functional tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by VitaliyBoyko — DISMISSED** [review]

**Comment by VitaliyBoyko** [comment]
@mmezhensky 

Are you up to proceed with this?

**Comment by mmezhensky** [comment]
@VitaliyBoyko 
Sorry, but I don't have time for this right now.
You can pick up this task if you need to push it faster.

**Review by eduard13 — APPROVED** [review]
Works great 👍 
@VitaliyBoyko do you have anything to add?

**Comment by VitaliyBoyko** [comment]
Yo so fast @eduard13 🤣

**Comment by VitaliyBoyko** [comment]
Teamwork

**Pull request merged**
