### PR TITLE
914: Updated readme file with information about sandbox creation

### PR DESCRIPTION
**Pull request by doninAtwix**
**Description** (*)

Updated readme file with information about sandbox creation.

**Fixed Issues (if relevant)**

1. Fixes magento/magento2-phpstorm-plugin#914

**Contribution checklist** (*)
 - [ ] Pull request has a meaningful description of its purpose
 - [ ] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with integration/functional tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Review by bohdan-harniuk — APPROVED** [review]
Hello, @doninAtwix!

Thank you for your work here! Looks good!

**Comment by doninAtwix** [comment]
@bohdan-harniuk Yes, I'm sign Adobe CLA. Could you please check again? Thank you

**Comment by bohdan-harniuk** [comment]
@doninAtwix, unfortunately it is still unsigned.

**Comment by doninAtwix** [comment]
@bohdan-harniuk Adobe CLA updated. Could you please check again? Thank you

**Comment by bohdan-harniuk** [comment]
@doninAtwix, everything is fine now! Thank you!

**Pull request merged**
