### PR TITLE
Inject a view model to a block and a reference block from the context menu

### PR DESCRIPTION
**Pull request by VitaliyBoyko**
**Description** (*)
This PR introduces functionality for injecting a view model to a block.

view-model-min

**Contribution checklist** (*)
 - [x] Pull request has a meaningful description of its purpose
 - [x] All commits are accompanied by meaningful commit messages
 - [ ] All new or changed code is covered with integration/functional tests (if applicable)
 - [ ] All automated tests passed successfully (all builds are green)

### CODE REVIEW

**Comment by coderimus** [comment]
**MAINTAINER REWARD CONCLUSION**

@VitaliyBoyko provides a significant change to the PHPStorm Magento plugin with adding a new feature allowing a view model generation. This work required from him high-quality technical expertise in writing code for the PHPStrom plugin, testing application. This new feature represents Magento 2 best technical vision practise, and this is why I set 2 awards: `Complex` and `Category of expertise`.

**Comment by VitaliyBoyko** [comment]
Hi @coderimus 

>A view model directory can contain only digitals. This looks like a wrong approach for the namespaces.
Well, this is not restricted by the framework. We need to support it.

Thanks!

**Comment by coderimus** [comment]
Hi @VitaliyBoyko ,

Got it, thank you. Ok, then the second reported issue is invalid. Please, ignore it. Implement just the first one. As a suggestion, we can name the parameter as view model class name in the snake case. As I remember we already have this functionality implemented.

**Comment by VitaliyBoyko** [comment]
Hi @coderimus 

I've adjusted the argument name autocomplete:
viewModelEnhanced-min

Thank you!

**Pull request merged**
