### PR TITLE
ISSUE-8: NullPointerException

### PR DESCRIPTION
**Pull request by voleye**
Fixes https://github.com/magento/magento2-phpstorm-plugin/issues/8

### CODE REVIEW

**Comment by riconeitzel** [comment]
anyone eager to merge that one?

**Comment by zolthan** [comment]
Is there any estimation when the bug will be fixed and released?

**Comment by lemaryn** [comment]
Can you tell please when it will be fixed?

**Comment by quisse** [comment]
BUMP

**Comment by wildcard27** [comment]
The bug turn around time with @magento-team is exceptional 🙄

**Comment by Vinai** [comment]
🔥 bump

**Pull request merged**
